# Generated by Django 4.0.2 on 2022-02-08 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destination',
            options={'verbose_name': 'Destination', 'verbose_name_plural': 'Destinations'},
        ),
        migrations.RemoveField(
            model_name='busroute',
            name='added_by',
        ),
    ]
