# Generated by Django 4.0.2 on 2022-02-08 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_destination_options_remove_busroute_added_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busroute',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='is_deleted',
        ),
    ]
