# Generated by Django 4.0.2 on 2022-02-10 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_remove_busroute_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='busroute',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
